version: '3.8'

services:
  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: DB_DIGITAL_WORLD
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./Back/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - DIGITAL_WORLD

  frontend:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./Front:/usr/share/nginx/html
    networks:
      - DIGITAL_WORLD

  backend:
    build: ./Back
    ports:
      - "5000:5000"
    depends_on:
      - db
    volumes:
      - ./Back:/app
    networks:
      - DIGITAL_WORLD


volumes:
  mariadb_data:

networks:
  DIGITAL_WORLD:
